Feature/unblock
Swent-team-6/icebreakrr pull request #142
Opened 2024-11-18 20:41 UTC by louiscrc

# New Feature : unblock Profiles
## UI
The UI is quite similar to the AroundYou page, except it displays user cards of users you blocked rather than regular users. 

Also, the TopBar is thinner as it's not a BottomNavigation page. And of course there is no Filter button.

Finally, new button in the Settings to replace the old `Unblock All` button, which gives access to the UnblockProfile screen.

## Back-end
Few changes in the back-end:

- ``getBlockedProfiles``: new function in the ProfileViewModel that triggers the same function in ProfilesRepositoryFirebase to get the Profiles of the users in `hasBlocked` from the database.
- ``unblockUser``: new function in the ProfileViewModel that deletes removes a the uid parameter from the hasBlocked list of the selfProfile.

2024-11-21 17:25 UTC, BotondAKovacs requested changes
Good PR overall, it works perfectly, there are however some nitpicks that can easily be fixed, like hardcoded strings and numbers and also a suggestion to use a shared ui component.
Tests are lacking for now.
Question: I'm wondering what's better between not letting offline users see the blocklist and what you've done, which is letting them go there and display that the user is not connected. Maybe just putting a toast when trying to go on that screen makes more sense. What do you think?

The topbar is incoherent with the rest of the app but my suggestion should fix that. 
Questions: Is the bottom navigation bar needed? 
<img width="282" alt="Screenshot 2024-11-21 at 18 21 53" src="https://github.com/user-attachments/assets/8e939556-96e0-4aca-b16c-53f63abf1dde">

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/Settings.kt
> +            Text("See unblock", color = Color.White)
Nitpick: Hardcoded string could be put in Strings.xml

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +                  Text("Yes")
Nitpick: Hardcoded string could be put in Strings.xml

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +                  Text("No")
Nitpick: Hardcoded string could be put in Strings.xml

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +        delay(10_000L)
Nitpick: magic number

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +              title = { Text("Blocked Users",color= Color.White, modifier = Modifier.testTag("UnblockTopBarTitle")) },
Nitpick: Hardcoded string could be put in Strings.xml

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +          TopAppBar(
You could use the standardized topBar we have in Ui/Shared

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +                                  text = "No Internet Connection",
Nitpick: Hardcoded string could be put in Strings.xml or there might already be one for this I think.

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +          text = { Text("Are you sure you want to unblock ${profileToUnblock!!.name}?") },
Nitpick: Hardcoded string could be put in Strings.xml

2024-11-21 17:25 UTC, BotondAKovacs commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/UnblockProfile.kt
> +          title = { Text("Confirm Unblock") },
Nitpick: Hardcoded string could be put in Strings.xml

2024-11-21 22:35 UTC, louiscrc commented
Though I agree with you for the TopBar component, this needs to be stated as an issue and fixed later. The current TopBar doesn't allow a goBack button...

2024-11-21 22:40 UTC, BotondAKovacs commented
> Though I agree with you for the TopBar component, this needs to be stated as an issue and fixed later. The current TopBar doesn't allow a goBack button...

I pushed the new one to the main yesterday

2024-11-21 22:47 UTC, louiscrc commented
> > Though I agree with you for the TopBar component, this needs to be stated as an issue and fixed later. The current TopBar doesn't allow a goBack button...
> 
> I pushed the new one to the main yesterday

Indeed, I merged the main into my branch and saw it. I'll implement it.

2024-11-21 23:22 UTC, BotondAKovacs commented
The dialog seems broken in the last version
<img width="290" alt="image" src="https://github.com/user-attachments/assets/8ced259f-727c-4842-a95d-d8464a111c07">

2024-11-22 00:04 UTC, BotondAKovacs approved these changes
You should link this PR to a scrumboard issue and the coverage could be improved in the future, apart from that LGTM

2024-11-22 00:11 UTC, BotondAKovacs approved these changes
LGTM

2024-11-22 00:15 UTC, merged