Feature/authentication : Account creation & True user data display
Swent-team-6/icebreakrr pull request #56
Opened 2024-11-03 17:53 UTC by JanStaszewiczEPFL

### PR Summary

This pull request enhances the profile and sign-in experience by introducing the following key changes:

**Account Creation on First Sign-In:**

- Added functionality to create an account automatically upon the user’s first sign-in in the `SignIn` screen.

**Display True User Data in Profile Screens:**

- Adjusted both `ProfileView` to display true user data.
- Adjusted both `OtherProfileView` to display true user data.
- Refactored `MainActivity` to adapt to the updated profile screen parameters and ensure proper data flow.
- Updated `AroundYou` screen to pass the user id as a navigation parameters to display true user data in `OtherProfileView`.
- Updated the `Settings` screens to display actual user data on profile cards.

**Tests Implemented**

- Created comprehensive unit tests for ProfileView and OtherProfileView to cover various states, including loading indicators, data display, and user interactions. This required the creation of a `MockProfileRepository` in `MockProfileBackend` to adapt `MockProfileViewModel` to allow the injection of a mock profile and disabling loading during test.
- Adapted Settings screen tests to pass the necessary parameters for displaying true user data on profile cards.
- Modified navigation tests in AroundYou to account for the new profile loading state, ensuring accurate flow and assertions.
- Updated AroundYou screen tests to handle user ID parameters when interacting with profile cards.
- Added tests for account creation during the sign-in process to confirm successful user onboarding.

**Additional Refactoring**

- Made some ProfilesViewModel parameters open to facilitate testing and ensure accessibility for mocks.

2024-11-03 21:12 UTC, Kapestian requested changes
Your solution seems to work, I left a few (for real it's not much) comments, but there is a big code smell (the hotfix of profile repository) to (un)correct absolutely. Please read them and tell me when you're done. 

Nice work buddy!

2024-11-03 21:12 UTC, Kapestian commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/shared/DisplayProfile.kt
> -            painter = painterResource(id = R.drawable.turtle),
😢

2024-11-03 21:15 UTC, SamSteu requested changes
Good code in general

Except for the bad coverage but this must be an issue with SonarCloud from your side. Since you have a really good coverage when running Jacoco on local I guess it is fine.

2024-11-04 12:06 UTC, JanStaszewiczEPFL commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/Settings.kt
> +          if (profile != null) {
There is no loading system implemented inside the cards.

2024-11-04 12:21 UTC, JanStaszewiczEPFL commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/AroundYou.kt
> +                                      "?userId=${filteredProfiles.value[index].uid}")
It is working like web urls. You can pass navigation params to a screen with the same syntax as in web, you start with "?" to announce your variables and then write `varName=value` to set the value. During navigation the url would be something like `SCREEN_NAME?userId=1234`. You can then retrieve this value in the corresponding screen using the `NavBackStack` class with `val profileId = navBackStackEntry?.arguments?.getString("userId")` (see top of `OtherProfileView.kt`).

2024-11-04 12:22 UTC, JanStaszewiczEPFL commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/shared/DisplayProfile.kt
> -            painter = painterResource(id = R.drawable.turtle),
It's a sad day for IceBreakrr :(

2024-11-04 12:22 UTC, JanStaszewiczEPFL commented on app/src/main/java/com/github/se/icebreakrr/ui/authentication/SignIn.kt
> +                  Log.i("SignIn", "Creating new user: ${newProfile.name}")
You are right!

2024-11-04 12:31 UTC, JanStaszewiczEPFL commented on app/src/main/java/com/github/se/icebreakrr/ui/authentication/SignIn.kt
> +                  Log.i("SignIn", "Profile exists: ${profile.name}")
You detect the small issues like an eagle! That's some great advice thank's!

2024-11-04 12:53 UTC, Kapestian approved these changes
2nd review: LGTM

2024-11-04 12:58 UTC, JanStaszewiczEPFL commented
![image](https://github.com/user-attachments/assets/06e5cf4a-b8b9-4730-99bb-b825fc4d7fa2)
Please review me :(

2024-11-04 13:31 UTC, merged