Hotfix/increase UI coverage
Swent-team-6/icebreakrr pull request #78
Opened 2024-11-10 19:09 UTC by MaxCastelCast

This request if to fix some minor bugs and increase overall coverage :
- Add tests for the MeetingRequestViewModel
- Repair the MeetingRequestService to make it able to change the new fcm tokens and set them in the backend
- repair the NavigationTest

2024-11-10 22:55 UTC, Kapestian requested changes
Thanks for your PR, I know fixes are not the most exiting task but you did a great job that made our app more stable and robust. 
I will just ask you to document your PR a bit more to make the review and future modification of the code easier. Also, there are some handling of null values that look odd, maybe I am getting it wrong and if it's the case don't hesitate to tell me why.

Future improvement: Using Ai and StackOverflow, I learned that some of your code could benefit from dependencies injection (e.g the MeetingRequestManager would not be needed). As I am far from being an expert in this domain, I think we should have a talk about Hilt with the team and evaluate if it is profitable to update our project with dependencies injection.

Tell me when you are ready for another round, I'll review your changes in no time.

Keep going bud!

2024-11-10 22:55 UTC, Kapestian commented on app/src/main/java/com/github/se/icebreakrr/model/message/MeetingRequestManager.kt
Docs: I am not sure to understand how this works. Could you provide more documentation?

2024-11-10 22:55 UTC, Kapestian commented on app/src/main/java/com/github/se/icebreakrr/MainActivity.kt
> +        profileViewModel, tagsViewModel, filterViewModel, meetingRequestViewModel, Route.AUTH)
Docs: Could you add more comments in that part as it is really hard for a "notification newbie" to understand what's done here

2024-11-10 22:55 UTC, Kapestian commented on app/src/main/java/com/github/se/icebreakrr/model/message/MeetingRequestService.kt
> +    Log.d("FIRESTORE KEY", "key changed by Firestore")
task: remove debugging log if not needed

2024-11-10 22:55 UTC, Kapestian commented on app/src/main/java/com/github/se/icebreakrr/ui/sections/Notifications.kt
> +            selectedItem = navigationActions.currentRoute())
wrong fix: Thanks for solving my issue, but on friday's meeting the coaches told us it was better to have the current screen's icon highlighted in the navigation menu. You need to unfix this and apply the selection highlight for every screen's icon. you will also need to make the icon's background less bright

![image](https://github.com/user-attachments/assets/bf0d68e2-c773-4828-bdff-eb582ef2fec7) TOO WHITE!

2024-11-11 01:05 UTC, MaxCastelCast commented
New fix incomming : Stop  the image bliping problem when you click on the Notification button when you are already in the Notification screen

2024-11-11 11:03 UTC, Kapestian approved these changes
Thanks for applying the changes!

2024-11-11 11:04 UTC, merged